//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournamental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int Id { get; set; }
        public int Tournament { get; set; }
        public int User { get; set; }
        public string LicenceNumber { get; set; }
        public int CurrentRanking { get; set; }
    
        public virtual Tournament Tournament1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
