//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournamental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Participant = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Discipline { get; set; }
        public int Organizer { get; set; }
        public System.DateTime Time { get; set; }
        public string Location { get; set; }
        public int MaxParticipant { get; set; }
        public System.DateTime ApplicationDeadline { get; set; }
        public string SponsorLogo { get; set; }
        public int RankedPlayers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participant { get; set; }
    }
}
